version: '3.7'
services:
  app:
    build: ./
    container_name: app
    working_dir: /var/www
    volumes:
      - ./ride/:/var/www
    ports:
      - '9000:9000'
    networks:
      - app-php
    depends_on:
      - database
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./ride:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php
  database:
    image: postgres:16.0-alpine
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: '123456'
    volumes:
      - './docker/database:/scripts'
      - 'pgdata:/var/lib/postgresql/data'
    networks:
      - app-php
networks:
  app-php:
    driver: bridge
volumes:
  pgdata: